# workflow name
name: CI

# trigger events
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# jobs to run
jobs:

  # job: build and run CLI application
  build:
    name: Build and run CLI application
    needs: test
    runs-on: ubuntu-latest
    steps:
      
      # step 1: set up go
      - name: Set up Go 1.23
        uses: actions/setup-go@v1
        with:
          go-version: 1.23
      
      # step 2: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      # step 3: install dependencies
      - name: Install all Go dependencies
        run: go get
      
      # step 4: build module
      - name: go build
        run: go build

      # step 5: execute a sample command
      - name: ./ripit [options]
        run: ./ripit --help
      
